version: '3.8'

services:
  app:
    image: iramsregistry.azurecr.io/irams:latest
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - AZURE_HOST=${AZURE_HOST}
      - AZURE_FRONTEND_URL=${AZURE_FRONTEND_URL}
      - SETUP_TOKEN=${SETUP_TOKEN}
    restart: always