# Generated by Django 6.0.1 on 2026-02-05 05:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.CharField(max_length=50, unique=True)),
                ('district', models.CharField(max_length=50)),
                ('road_class', models.CharField(max_length=50)),
                ('road_type', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('pop_within_2km', models.IntegerField(default=0)),
                ('has_hospital', models.BooleanField(default=False)),
                ('has_school', models.BooleanField(default=False)),
                ('is_only_access', models.BooleanField(default=False)),
                ('latest_ddi_score', models.FloatField(default=0.0)),
                ('current_mca_score', models.FloatField(default=0.0)),
                ('priority_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=100, unique=True)),
                ('source_video_url', models.URLField()),
                ('total_pothole_count', models.IntegerField(default=0)),
                ('total_crack_count', models.IntegerField(default=0)),
                ('calculated_ddi', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roads.roadsegment')),
            ],
        ),
    ]
