# Generated by Django 6.0.1 on 2026-02-12 17:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsegment',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326),
        ),
    ]
