# Generated by Django 6.0.1 on 2026-02-15 19:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_alter_roadsegment_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326)),
            ],
        ),
    ]
