# Generated by Django 6.0.1 on 2026-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_nationalroad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsegment',
            name='has_hospital',
        ),
        migrations.RemoveField(
            model_name='roadsegment',
            name='has_school',
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='health_facility_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='school_count',
            field=models.IntegerField(default=0),
        ),
    ]
