# Generated by Django 6.0.1 on 2026-02-26 10:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_remove_roadsegment_has_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructurePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
