# Generated by Django 6.0.1 on 2026-03-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0005_infrastructurepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_weight', models.FloatField(default=0.5)),
                ('criticality_weight', models.FloatField(default=0.5)),
                ('weight_population', models.FloatField(default=0.4)),
                ('weight_health', models.FloatField(default=0.2)),
                ('weight_education', models.FloatField(default=0.2)),
                ('weight_isolation', models.FloatField(default=0.2)),
                ('threshold_high', models.FloatField(default=4.0)),
                ('threshold_medium', models.FloatField(default=2.5)),
                ('last_updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Algorithm Configuration',
            },
        ),
    ]
